name: Check Links

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-mail -- '*.html' '**/*.html' '**/*.md'
          output: true
          fail: true
